// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: grpc/block/blockpb/block.proto

package blockpb

import (
	context "context"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Header struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	ParentHash           string               `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Height               int64                `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	StateRoot            string               `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ExtrinsicsRoot       string               `protobuf:"bytes,5,opt,name=extrinsics_root,json=extrinsicsRoot,proto3" json:"extrinsics_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa3e78aae19c108, []int{0}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_block_blockpb_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_grpc_block_blockpb_block_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (m *Header) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (x *Header) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *Header) GetExtrinsicsRoot() string {
	if x != nil {
		return x.ExtrinsicsRoot
	}
	return ""
}

type Extrinsic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExtrinsicIndex      int64  `protobuf:"varint,1,opt,name=extrinsic_index,json=extrinsicIndex,proto3" json:"extrinsic_index,omitempty"`
	Hash                string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Time                string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	IsSignedTransaction bool   `protobuf:"varint,4,opt,name=is_signed_transaction,json=isSignedTransaction,proto3" json:"is_signed_transaction,omitempty"`
	Signature           string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer              string `protobuf:"bytes,6,opt,name=signer,proto3" json:"signer,omitempty"`
	Nonce               int64  `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Method              string `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	Section             string `protobuf:"bytes,9,opt,name=section,proto3" json:"section,omitempty"`
	Args                string `protobuf:"bytes,10,opt,name=args,proto3" json:"args,omitempty"`
	IsSuccess           bool   `protobuf:"varint,11,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	PartialFee          string `protobuf:"bytes,12,opt,name=partialFee,proto3" json:"partialFee,omitempty"`
	Tip                 string `protobuf:"bytes,13,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *Extrinsic) Reset() {
	*x = Extrinsic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_block_blockpb_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extrinsic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extrinsic) ProtoMessage() {}

func (x *Extrinsic) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_block_blockpb_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extrinsic.ProtoReflect.Descriptor instead.
func (*Extrinsic) Descriptor() ([]byte, []int) {
	return file_grpc_block_blockpb_block_proto_rawDescGZIP(), []int{1}
}

func (x *Extrinsic) GetExtrinsicIndex() int64 {
	if x != nil {
		return x.ExtrinsicIndex
	}
	return 0
}

func (x *Extrinsic) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Extrinsic) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Extrinsic) GetIsSignedTransaction() bool {
	if x != nil {
		return x.IsSignedTransaction
	}
	return false
}

func (x *Extrinsic) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Extrinsic) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *Extrinsic) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Extrinsic) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Extrinsic) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Extrinsic) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Extrinsic) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type Block struct {
	BlockHash            string       `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Header               *Header      `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Extrinsics           []*Extrinsic `protobuf:"bytes,3,rep,name=extrinsics,proto3" json:"extrinsics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (x *Extrinsic) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *Header      `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Extrinsics []*Extrinsic `protobuf:"bytes,3,rep,name=extrinsics,proto3" json:"extrinsics,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_block_blockpb_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_block_blockpb_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_grpc_block_blockpb_block_proto_rawDescGZIP(), []int{2}
}

func (m *Block) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Block) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (x *Block) GetExtrinsics() []*Extrinsic {
	if x != nil {
		return x.Extrinsics
	}
	return nil
}

type GetByHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetByHeightRequest) Reset() {
	*x = GetByHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_block_blockpb_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByHeightRequest) ProtoMessage() {}

func (x *GetByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_block_blockpb_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByHeightRequest.ProtoReflect.Descriptor instead.
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return file_grpc_block_blockpb_block_proto_rawDescGZIP(), []int{3}
}

func (x *GetByHeightRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa3e78aae19c108, []int{4}
}

func (x *GetByHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByHeightResponse) ProtoMessage() {}

func (x *GetByHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_block_blockpb_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByHeightResponse.ProtoReflect.Descriptor instead.
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return file_grpc_block_blockpb_block_proto_rawDescGZIP(), []int{4}
}

func (m *GetByHeightResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "block.Header")
	proto.RegisterType((*Extrinsic)(nil), "block.Extrinsic")
	proto.RegisterType((*Block)(nil), "block.Block")
	proto.RegisterType((*GetByHeightRequest)(nil), "block.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "block.GetByHeightResponse")
}

func init() { proto.RegisterFile("grpc/block/blockpb/block.proto", fileDescriptor_6fa3e78aae19c108) }

var fileDescriptor_6fa3e78aae19c108 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x75, 0x93, 0xd6, 0xe3, 0xf2, 0xa1, 0x2d, 0x20, 0x13, 0x01, 0x8d, 0x2c, 0x21, 0x72,
	0xa0, 0x36, 0x0a, 0x27, 0x6e, 0x28, 0x12, 0x10, 0xae, 0x4e, 0xc5, 0x81, 0x4b, 0xb4, 0x71, 0xa6,
	0xf6, 0x2a, 0xc9, 0xae, 0xd9, 0xdd, 0x40, 0x7a, 0xe2, 0x77, 0x71, 0xe4, 0x9f, 0xa1, 0x9d, 0x75,
	0x88, 0xab, 0x72, 0x49, 0x3c, 0x6f, 0xde, 0xb3, 0xdf, 0xec, 0xbc, 0x85, 0x97, 0x95, 0x6e, 0xca,
	0x7c, 0xb1, 0x56, 0xe5, 0xca, 0xff, 0x36, 0x0b, 0xff, 0x9f, 0x35, 0x5a, 0x59, 0xc5, 0x7a, 0x54,
	0x0c, 0x2e, 0x2a, 0xa5, 0xaa, 0x35, 0xe6, 0x04, 0x2e, 0xb6, 0xd7, 0xb9, 0x15, 0x1b, 0x34, 0x96,
	0x6f, 0x1a, 0xcf, 0x4b, 0x7f, 0x07, 0xd0, 0x9f, 0x22, 0x5f, 0xa2, 0x66, 0x19, 0x1c, 0xbb, 0x6e,
	0x12, 0x0c, 0x83, 0x51, 0x3c, 0x1e, 0x64, 0x5e, 0x9a, 0xed, 0xa5, 0xd9, 0xd5, 0x5e, 0x5a, 0x10,
	0x8f, 0x5d, 0x40, 0xdc, 0x70, 0x8d, 0xd2, 0xce, 0x6b, 0x6e, 0xea, 0xe4, 0x68, 0x18, 0x8c, 0xa2,
	0x02, 0x3c, 0x34, 0xe5, 0xa6, 0x66, 0x4f, 0xa1, 0x5f, 0xa3, 0xa8, 0x6a, 0x9b, 0x84, 0xc3, 0x60,
	0x14, 0x16, 0x6d, 0xc5, 0x5e, 0x00, 0x18, 0xcb, 0x2d, 0xce, 0xb5, 0x52, 0x36, 0x39, 0x26, 0x5d,
	0x44, 0x48, 0xa1, 0x94, 0x65, 0xaf, 0xe1, 0x21, 0xee, 0xac, 0x16, 0xd2, 0x88, 0xd2, 0x78, 0x4e,
	0x8f, 0x38, 0x0f, 0x0e, 0xb0, 0x23, 0xa6, 0x7f, 0x8e, 0x20, 0xfa, 0xb8, 0x87, 0x6e, 0xc9, 0xe6,
	0x42, 0x2e, 0x71, 0x47, 0x93, 0x84, 0x1d, 0xd9, 0x17, 0x87, 0x32, 0x06, 0xc7, 0x1d, 0xc3, 0xf4,
	0xec, 0x30, 0x9a, 0x3d, 0xf4, 0x18, 0xcd, 0x37, 0x86, 0x27, 0xc2, 0xcc, 0x8d, 0xa8, 0x24, 0x2e,
	0xe7, 0x56, 0x73, 0x69, 0x78, 0x69, 0x85, 0x92, 0xe4, 0xf8, 0xb4, 0x38, 0x17, 0x66, 0x46, 0xbd,
	0xab, 0x43, 0x8b, 0x3d, 0x87, 0xc8, 0x09, 0xb8, 0xdd, 0x6a, 0x6c, 0x5d, 0x1f, 0x00, 0x77, 0x20,
	0xf4, 0x3a, 0x9d, 0xf4, 0xa9, 0xd5, 0x56, 0xec, 0x31, 0xf4, 0xa4, 0x92, 0x25, 0x26, 0x27, 0x64,
	0xd8, 0x17, 0x8e, 0xbd, 0x41, 0x5b, 0xab, 0x65, 0x72, 0xea, 0xd9, 0xbe, 0x62, 0x09, 0x9c, 0x18,
	0xf4, 0x4e, 0x22, 0x6a, 0xec, 0x4b, 0x37, 0x05, 0xd7, 0x95, 0x49, 0xc0, 0x4f, 0xe1, 0x9e, 0xdd,
	0x61, 0xbb, 0x29, 0xb6, 0x65, 0x89, 0xc6, 0x24, 0x31, 0x59, 0x8f, 0x84, 0x99, 0x79, 0x20, 0xfd,
	0x05, 0xbd, 0x89, 0x4b, 0x8a, 0xe3, 0x51, 0x64, 0xfc, 0x32, 0x03, 0x6f, 0x9d, 0x10, 0xda, 0xe5,
	0x2b, 0xb7, 0x4b, 0x17, 0x13, 0x3a, 0xb6, 0x78, 0x7c, 0x3f, 0xf3, 0x69, 0xf3, 0xd9, 0x29, 0xda,
	0x26, 0x7b, 0x0b, 0x70, 0x58, 0x52, 0x12, 0x0e, 0xc3, 0x51, 0x3c, 0x7e, 0xd4, 0x52, 0xff, 0xad,
	0xaa, 0xe8, 0x70, 0xd2, 0x37, 0xc0, 0x3e, 0xa3, 0x9d, 0xdc, 0x4c, 0x29, 0x1b, 0x05, 0x7e, 0xdf,
	0xa2, 0xb1, 0x9d, 0xe8, 0x04, 0xdd, 0xe8, 0xa4, 0xef, 0xe1, 0xfc, 0x16, 0xdb, 0x34, 0x4a, 0x1a,
	0x64, 0x29, 0xf8, 0xbc, 0xb7, 0xd9, 0x3d, 0x6b, 0xbf, 0x48, 0x93, 0x15, 0xbe, 0x35, 0xfe, 0x0a,
	0x67, 0x54, 0xcf, 0x50, 0xff, 0x10, 0x25, 0xb2, 0x4f, 0x10, 0x77, 0x5e, 0xc5, 0x9e, 0xb5, 0x9a,
	0xbb, 0x66, 0x06, 0x83, 0xff, 0xb5, 0xfc, 0x97, 0xd3, 0x7b, 0x93, 0xc9, 0xb7, 0x0f, 0x95, 0xb0,
	0xf5, 0x76, 0x91, 0x95, 0x6a, 0x93, 0x5f, 0x8b, 0x6a, 0x83, 0xd2, 0x5e, 0x4a, 0xb4, 0x3f, 0x95,
	0x5e, 0x99, 0xbc, 0x51, 0xeb, 0x15, 0x5f, 0x2a, 0x47, 0xb8, 0x6c, 0xb4, 0xda, 0xdd, 0xe4, 0x77,
	0x6f, 0xee, 0xa2, 0x4f, 0x97, 0xec, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xfd, 0x5f,
	0x4e, 0xd6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlockServiceClient is the client API for BlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type blockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockServiceClient(cc grpc.ClientConnInterface) BlockServiceClient {
	return &blockServiceClient{cc}
}

func (c *blockServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/block.BlockService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockServiceServer is the server API for BlockService service.
type BlockServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockServiceServer struct {
}

func (*UnimplementedBlockServiceServer) GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterBlockServiceServer(s *grpc.Server, srv BlockServiceServer) {
	s.RegisterService(&_BlockService_serviceDesc, srv)
}

func _BlockService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/block.BlockService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "block.BlockService",
	HandlerType: (*BlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _BlockService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/block/blockpb/block.proto",
}
