// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/validatorperformance/validatorperformancepb/validator_performance.proto

package validatorperformancepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Validator struct {
	StashAccount         string   `protobuf:"bytes,1,opt,name=stash_account,json=stashAccount,proto3" json:"stash_account,omitempty"`
	Online               bool     `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_3278576864b3645d, []int{0}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetStashAccount() string {
	if m != nil {
		return m.StashAccount
	}
	return ""
}

func (m *Validator) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3278576864b3645d, []int{1}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3278576864b3645d, []int{2}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*Validator)(nil), "validatorPerformance.Validator")
	proto.RegisterType((*GetByHeightRequest)(nil), "validatorPerformance.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "validatorPerformance.GetByHeightResponse")
}

func init() {
	proto.RegisterFile("grpc/validatorperformance/validatorperformancepb/validator_performance.proto", fileDescriptor_3278576864b3645d)
}

var fileDescriptor_3278576864b3645d = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xbf, 0x7c, 0x95, 0x2a, 0xea, 0xc2, 0x62, 0x10, 0xaa, 0x60, 0x20, 0x0a, 0x4b, 0x90,
	0x68, 0x22, 0x95, 0x1f, 0x80, 0xe8, 0x42, 0x07, 0x06, 0x14, 0xa4, 0x0c, 0x0c, 0x14, 0xc7, 0xb9,
	0x26, 0x56, 0x13, 0x9f, 0xb1, 0x9d, 0x42, 0x67, 0xfe, 0x38, 0x22, 0x2d, 0x69, 0x10, 0x19, 0x60,
	0xbc, 0xe7, 0x1e, 0x9f, 0xdf, 0xd3, 0x91, 0xbb, 0x4c, 0x2b, 0x1e, 0xae, 0x58, 0x21, 0x52, 0x66,
	0x51, 0x2b, 0xd0, 0x0b, 0xd4, 0x25, 0x93, 0x1c, 0x3a, 0xa1, 0x4a, 0x76, 0x78, 0xde, 0xe2, 0x81,
	0xd2, 0x68, 0x91, 0x1e, 0x35, 0xcd, 0xfb, 0x5d, 0xcf, 0x9b, 0x91, 0x41, 0xfc, 0xc5, 0xe9, 0x39,
	0x39, 0x30, 0x96, 0x99, 0x7c, 0xce, 0x38, 0xc7, 0x4a, 0xda, 0x91, 0xe3, 0x3a, 0xfe, 0x20, 0xda,
	0xaf, 0xe1, 0xcd, 0x86, 0xd1, 0x63, 0xd2, 0x47, 0x59, 0x08, 0x09, 0xa3, 0xff, 0xae, 0xe3, 0xef,
	0x45, 0xdb, 0xca, 0xbb, 0x24, 0xf4, 0x16, 0xec, 0x74, 0x3d, 0x03, 0x91, 0xe5, 0x36, 0x82, 0x97,
	0x0a, 0x4c, 0x6d, 0xe7, 0x35, 0xa8, 0x67, 0xf5, 0xa2, 0x6d, 0xe5, 0xc5, 0xe4, 0xf0, 0x9b, 0x6d,
	0x14, 0x4a, 0x03, 0xf4, 0x9a, 0x90, 0x26, 0xa6, 0x19, 0x39, 0x6e, 0xcf, 0x1f, 0x4e, 0xce, 0x82,
	0xae, 0xe4, 0x41, 0x13, 0x3b, 0x6a, 0x3d, 0x99, 0xbc, 0x3b, 0xe4, 0x34, 0xee, 0xd0, 0x1f, 0x40,
	0xaf, 0x04, 0x07, 0x9a, 0x92, 0x61, 0xeb, 0x5f, 0xea, 0x77, 0xcf, 0xfe, 0xb9, 0xc8, 0xc9, 0xc5,
	0x2f, 0xcc, 0xcd, 0x12, 0xde, 0xbf, 0xe9, 0xf3, 0xe3, 0x53, 0x26, 0x6c, 0x5e, 0x25, 0x01, 0xc7,
	0x32, 0x5c, 0x88, 0xac, 0x04, 0x69, 0xc7, 0x12, 0xec, 0x2b, 0xea, 0xa5, 0x09, 0x15, 0x16, 0x4b,
	0x96, 0xe2, 0xa7, 0x30, 0x56, 0x1a, 0xdf, 0xd6, 0xe1, 0x5f, 0x2f, 0x9d, 0xf4, 0xeb, 0xa3, 0x5e,
	0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x91, 0x5b, 0x9d, 0x4c, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ValidatorPerformanceServiceClient is the client API for ValidatorPerformanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidatorPerformanceServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type validatorPerformanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorPerformanceServiceClient(cc grpc.ClientConnInterface) ValidatorPerformanceServiceClient {
	return &validatorPerformanceServiceClient{cc}
}

func (c *validatorPerformanceServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/validatorPerformance.ValidatorPerformanceService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorPerformanceServiceServer is the server API for ValidatorPerformanceService service.
type ValidatorPerformanceServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedValidatorPerformanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedValidatorPerformanceServiceServer struct {
}

func (*UnimplementedValidatorPerformanceServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterValidatorPerformanceServiceServer(s *grpc.Server, srv ValidatorPerformanceServiceServer) {
	s.RegisterService(&_ValidatorPerformanceService_serviceDesc, srv)
}

func _ValidatorPerformanceService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorPerformanceServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validatorPerformance.ValidatorPerformanceService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorPerformanceServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValidatorPerformanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "validatorPerformance.ValidatorPerformanceService",
	HandlerType: (*ValidatorPerformanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _ValidatorPerformanceService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/validatorperformance/validatorperformancepb/validator_performance.proto",
}
