// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/transaction/transactionpb/transaction.proto

package transactionpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	ExtrinsicIndex       int64    `protobuf:"varint,1,opt,name=extrinsic_index,json=extrinsicIndex,proto3" json:"extrinsic_index,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer               string   `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Nonce                int64    `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Method               string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Section              string   `protobuf:"bytes,6,opt,name=section,proto3" json:"section,omitempty"`
	Args                 string   `protobuf:"bytes,7,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_085b31815091ec91, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetExtrinsicIndex() int64 {
	if m != nil {
		return m.ExtrinsicIndex
	}
	return 0
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Transaction) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Transaction) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *Transaction) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_085b31815091ec91, []int{1}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_085b31815091ec91, []int{2}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*GetByHeightRequest)(nil), "transaction.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "transaction.GetByHeightResponse")
}

func init() {
	proto.RegisterFile("grpc/transaction/transactionpb/transaction.proto", fileDescriptor_085b31815091ec91)
}

var fileDescriptor_085b31815091ec91 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0xf9, 0xa7, 0x4d, 0xd5, 0x0b, 0x02, 0xe9, 0x40, 0xe8, 0x84, 0x10, 0x44, 0x59,
	0xc8, 0x80, 0x0a, 0x2a, 0x2b, 0x53, 0x17, 0x60, 0x4d, 0x99, 0x58, 0x50, 0x9a, 0x9e, 0x12, 0x0f,
	0xd8, 0xc1, 0x76, 0x51, 0xf9, 0x86, 0x7c, 0x2c, 0x14, 0x27, 0x50, 0x47, 0x08, 0xb6, 0xfb, 0xbd,
	0x7b, 0x3a, 0x9f, 0xdf, 0xc1, 0x75, 0xa5, 0x9b, 0xf2, 0xca, 0xea, 0x42, 0x9a, 0xa2, 0xb4, 0x42,
	0x49, 0xbf, 0x6e, 0x56, 0x3e, 0xcd, 0x1a, 0xad, 0xac, 0xc2, 0xd8, 0x93, 0xd2, 0x8f, 0x00, 0xe2,
	0xc7, 0x1d, 0xe3, 0x05, 0x1c, 0xf0, 0xd6, 0x6a, 0x21, 0x8d, 0x28, 0x9f, 0x85, 0x5c, 0xf3, 0x96,
	0x82, 0x24, 0xc8, 0xc2, 0x7c, 0xff, 0x5b, 0x7e, 0x68, 0x55, 0x3c, 0x85, 0xa9, 0x11, 0x95, 0x2c,
	0xec, 0x46, 0x33, 0xfd, 0x4f, 0x82, 0x6c, 0x9a, 0xef, 0x04, 0x3c, 0x86, 0xa8, 0x05, 0xd6, 0x14,
	0xba, 0x56, 0x4f, 0x78, 0x04, 0x63, 0xa9, 0x64, 0xc9, 0x34, 0x72, 0x43, 0x3b, 0x68, 0xdd, 0x2f,
	0x6c, 0x6b, 0xb5, 0xa6, 0x71, 0xe7, 0xee, 0x08, 0x09, 0x26, 0x86, 0xdd, 0x5e, 0x14, 0xb9, 0xc6,
	0x17, 0x22, 0xc2, 0xa8, 0xd0, 0x95, 0xa1, 0x89, 0x93, 0x5d, 0x9d, 0x5e, 0x02, 0xde, 0xb1, 0x5d,
	0xbc, 0xdf, 0xb3, 0xa8, 0x6a, 0x9b, 0xf3, 0xeb, 0x86, 0x8d, 0x6d, 0x67, 0xd7, 0x4e, 0xe8, 0xff,
	0xd1, 0x53, 0xba, 0x84, 0xc3, 0x81, 0xdb, 0x34, 0x4a, 0x1a, 0xc6, 0x5b, 0xd8, 0xf3, 0xe2, 0x31,
	0x14, 0x24, 0x61, 0x16, 0xcf, 0x69, 0xe6, 0xc7, 0xe8, 0xe5, 0x95, 0x0f, 0xdc, 0xf3, 0x1a, 0xd0,
	0x6b, 0x2e, 0x59, 0xbf, 0x89, 0x92, 0x31, 0x87, 0xd8, 0x7b, 0x0a, 0xcf, 0x07, 0xc3, 0x7e, 0xae,
	0x7c, 0x92, 0xfc, 0x6e, 0xe8, 0xb6, 0x4c, 0xff, 0x2d, 0x92, 0xa7, 0xb3, 0xbf, 0x0f, 0xbf, 0x8a,
	0xdc, 0xb5, 0x6f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x10, 0x95, 0x06, 0x21, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _TransactionService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/transaction/transactionpb/transaction.proto",
}
