// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/height/heightpb/height.proto

package heightpb

import (
	context "context"
	fmt "fmt"
	blockpb "github.com/figment-networks/polkadothub-proxy/grpc/block/blockpb"
	chainpb "github.com/figment-networks/polkadothub-proxy/grpc/chain/chainpb"
	eventpb "github.com/figment-networks/polkadothub-proxy/grpc/event/eventpb"
	stakingpb "github.com/figment-networks/polkadothub-proxy/grpc/staking/stakingpb"
	validatorperformancepb "github.com/figment-networks/polkadothub-proxy/grpc/validatorperformance/validatorperformancepb"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1593a49f769bc, []int{0}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetAllResponse struct {
	Chain                *chainpb.GetMetaByHeightResponse            `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Block                *blockpb.GetByHeightResponse                `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Staking              *stakingpb.GetByHeightResponse              `protobuf:"bytes,3,opt,name=staking,proto3" json:"staking,omitempty"`
	Event                *eventpb.GetByHeightResponse                `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	ValidatorPerformance *validatorperformancepb.GetByHeightResponse `protobuf:"bytes,5,opt,name=validator_performance,json=validatorPerformance,proto3" json:"validator_performance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1593a49f769bc, []int{1}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetChain() *chainpb.GetMetaByHeightResponse {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *GetAllResponse) GetBlock() *blockpb.GetByHeightResponse {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *GetAllResponse) GetStaking() *stakingpb.GetByHeightResponse {
	if m != nil {
		return m.Staking
	}
	return nil
}

func (m *GetAllResponse) GetEvent() *eventpb.GetByHeightResponse {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GetAllResponse) GetValidatorPerformance() *validatorperformancepb.GetByHeightResponse {
	if m != nil {
		return m.ValidatorPerformance
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAllRequest)(nil), "height.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "height.GetAllResponse")
}

func init() { proto.RegisterFile("grpc/height/heightpb/height.proto", fileDescriptor_acf1593a49f769bc) }

var fileDescriptor_acf1593a49f769bc = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0xdd, 0xe6, 0x26, 0x44, 0xe6, 0x43, 0x70, 0xa3, 0x0c, 0x19, 0x3a, 0x04, 0xf5, 0x61,
	0xad, 0x4c, 0x11, 0x7c, 0x74, 0x08, 0x13, 0x51, 0x90, 0xf9, 0xe6, 0x83, 0xd2, 0x74, 0xb7, 0xb6,
	0xb4, 0x6b, 0x62, 0x9a, 0x4d, 0xf7, 0xf5, 0xfc, 0x64, 0xb2, 0xbb, 0x54, 0x37, 0xed, 0x4b, 0x2e,
	0xb9, 0xff, 0xef, 0x92, 0xde, 0xbf, 0xc7, 0x8e, 0x42, 0xad, 0x02, 0x2f, 0x82, 0x38, 0x8c, 0x8c,
	0x0d, 0x4a, 0xd8, 0x8d, 0xab, 0xb4, 0x34, 0x92, 0x37, 0xe8, 0xd4, 0xe9, 0x22, 0x1a, 0x44, 0x7e,
	0x9c, 0xd1, 0xaa, 0x04, 0x45, 0xe2, 0xac, 0x2e, 0x52, 0x19, 0x24, 0xb4, 0x2a, 0x41, 0xd1, 0xea,
	0xc7, 0xa8, 0xe7, 0xc6, 0x4f, 0xe2, 0x2c, 0x2c, 0xa2, 0x12, 0xc5, 0xce, 0x52, 0x0f, 0x48, 0x2d,
	0xfc, 0x34, 0x9e, 0xf8, 0x46, 0x6a, 0x05, 0x7a, 0x2a, 0xf5, 0xcc, 0xcf, 0x02, 0x28, 0x4d, 0x2a,
	0xf1, 0x9b, 0x7e, 0x5b, 0xcb, 0x6f, 0x7c, 0x13, 0x2c, 0x20, 0x33, 0xb4, 0x2a, 0x41, 0x91, 0xf4,
	0xde, 0x09, 0x6b, 0x8e, 0xc0, 0xdc, 0xa4, 0xe9, 0x18, 0xde, 0xe7, 0x90, 0x1b, 0xde, 0x66, 0xb6,
	0x5d, 0xa7, 0x72, 0x58, 0x39, 0xad, 0x8d, 0xed, 0xa9, 0xf7, 0x55, 0x65, 0x7b, 0x05, 0x99, 0x2b,
	0x99, 0xe5, 0xc0, 0x2f, 0x59, 0x1d, 0xdb, 0x47, 0x72, 0x77, 0xd0, 0x75, 0xc9, 0x8c, 0x11, 0x98,
	0x47, 0x30, 0xfe, 0x70, 0x79, 0x87, 0x95, 0x05, 0x3e, 0x26, 0x98, 0x9f, 0xb3, 0x3a, 0x9a, 0xe2,
	0x54, 0xb1, 0xaa, 0xe3, 0x92, 0x45, 0x23, 0x30, 0xff, 0x2b, 0x50, 0xe2, 0x57, 0x6c, 0xc7, 0x5a,
	0xe4, 0xd4, 0xb0, 0xe6, 0xc0, 0x2d, 0x2c, 0x2b, 0xab, 0x2a, 0xe0, 0xd5, 0x4b, 0xd8, 0xaa, 0xb3,
	0x6d, 0x5f, 0xa2, 0xc6, 0x4b, 0x5f, 0x42, 0x89, 0xbf, 0xb2, 0x56, 0xa9, 0x99, 0x4e, 0x1d, 0x6f,
	0x38, 0x73, 0x7f, 0xd4, 0xa7, 0x35, 0xa7, 0xcb, 0x2e, 0xdc, 0x2f, 0x23, 0x07, 0xf7, 0xac, 0x49,
	0xdc, 0x33, 0xe8, 0x45, 0x1c, 0x00, 0xbf, 0x66, 0x0d, 0x32, 0x95, 0xb7, 0x5c, 0x3b, 0x73, 0x1b,
	0xbf, 0xa3, 0xd3, 0xfe, 0x9b, 0xa6, 0xfb, 0x7b, 0x5b, 0xc3, 0xdb, 0x97, 0x61, 0x18, 0x9b, 0x68,
	0x2e, 0xdc, 0x40, 0xce, 0xbc, 0x69, 0x1c, 0xce, 0x20, 0x33, 0xfd, 0x0c, 0xcc, 0x87, 0xd4, 0x49,
	0xee, 0x29, 0x99, 0x26, 0xfe, 0x44, 0xae, 0x80, 0xbe, 0xd2, 0xf2, 0x73, 0xe9, 0x95, 0x0d, 0xba,
	0x68, 0xe0, 0x18, 0x5c, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xfc, 0x83, 0x6b, 0x07, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HeightServiceClient is the client API for HeightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeightServiceClient interface {
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type heightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeightServiceClient(cc grpc.ClientConnInterface) HeightServiceClient {
	return &heightServiceClient{cc}
}

func (c *heightServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/height.HeightService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeightServiceServer is the server API for HeightService service.
type HeightServiceServer interface {
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
}

// UnimplementedHeightServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHeightServiceServer struct {
}

func (*UnimplementedHeightServiceServer) GetAll(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterHeightServiceServer(s *grpc.Server, srv HeightServiceServer) {
	s.RegisterService(&_HeightService_serviceDesc, srv)
}

func _HeightService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeightServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/height.HeightService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeightServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeightService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "height.HeightService",
	HandlerType: (*HeightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _HeightService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/height/heightpb/height.proto",
}
