// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/staking/stakingpb/staking.proto

package stakingpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stake struct {
	StashAccount         string   `protobuf:"bytes,1,opt,name=stash_account,json=stashAccount,proto3" json:"stash_account,omitempty"`
	ControllerAccount    string   `protobuf:"bytes,2,opt,name=controller_account,json=controllerAccount,proto3" json:"controller_account,omitempty"`
	Stake                int64    `protobuf:"varint,3,opt,name=stake,proto3" json:"stake,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stake) Reset()         { *m = Stake{} }
func (m *Stake) String() string { return proto.CompactTextString(m) }
func (*Stake) ProtoMessage()    {}
func (*Stake) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6736eb38aebd97d, []int{0}
}

func (m *Stake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stake.Unmarshal(m, b)
}
func (m *Stake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stake.Marshal(b, m, deterministic)
}
func (m *Stake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stake.Merge(m, src)
}
func (m *Stake) XXX_Size() int {
	return xxx_messageInfo_Stake.Size(m)
}
func (m *Stake) XXX_DiscardUnknown() {
	xxx_messageInfo_Stake.DiscardUnknown(m)
}

var xxx_messageInfo_Stake proto.InternalMessageInfo

func (m *Stake) GetStashAccount() string {
	if m != nil {
		return m.StashAccount
	}
	return ""
}

func (m *Stake) GetControllerAccount() string {
	if m != nil {
		return m.ControllerAccount
	}
	return ""
}

func (m *Stake) GetStake() int64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

type Validator struct {
	StashAccount         string   `protobuf:"bytes,1,opt,name=stash_account,json=stashAccount,proto3" json:"stash_account,omitempty"`
	ControllerAccount    string   `protobuf:"bytes,2,opt,name=controller_account,json=controllerAccount,proto3" json:"controller_account,omitempty"`
	Commission           int64    `protobuf:"varint,3,opt,name=commission,proto3" json:"commission,omitempty"`
	RewardPoints         int64    `protobuf:"varint,4,opt,name=reward_points,json=rewardPoints,proto3" json:"reward_points,omitempty"`
	TotalStake           int64    `protobuf:"varint,5,opt,name=total_stake,json=totalStake,proto3" json:"total_stake,omitempty"`
	OwnStake             int64    `protobuf:"varint,6,opt,name=own_stake,json=ownStake,proto3" json:"own_stake,omitempty"`
	Stakers              []*Stake `protobuf:"bytes,7,rep,name=stakers,proto3" json:"stakers,omitempty"`
	SessionKeys          []string `protobuf:"bytes,8,rep,name=session_keys,json=sessionKeys,proto3" json:"session_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6736eb38aebd97d, []int{1}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetStashAccount() string {
	if m != nil {
		return m.StashAccount
	}
	return ""
}

func (m *Validator) GetControllerAccount() string {
	if m != nil {
		return m.ControllerAccount
	}
	return ""
}

func (m *Validator) GetCommission() int64 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func (m *Validator) GetRewardPoints() int64 {
	if m != nil {
		return m.RewardPoints
	}
	return 0
}

func (m *Validator) GetTotalStake() int64 {
	if m != nil {
		return m.TotalStake
	}
	return 0
}

func (m *Validator) GetOwnStake() int64 {
	if m != nil {
		return m.OwnStake
	}
	return 0
}

func (m *Validator) GetStakers() []*Stake {
	if m != nil {
		return m.Stakers
	}
	return nil
}

func (m *Validator) GetSessionKeys() []string {
	if m != nil {
		return m.SessionKeys
	}
	return nil
}

type Staking struct {
	Session              int64        `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Era                  int64        `protobuf:"varint,2,opt,name=era,proto3" json:"era,omitempty"`
	TotalStake           int64        `protobuf:"varint,3,opt,name=total_stake,json=totalStake,proto3" json:"total_stake,omitempty"`
	TotalRewardPayout    int64        `protobuf:"varint,4,opt,name=total_reward_payout,json=totalRewardPayout,proto3" json:"total_reward_payout,omitempty"`
	TotalRewardPoints    int64        `protobuf:"varint,5,opt,name=total_reward_points,json=totalRewardPoints,proto3" json:"total_reward_points,omitempty"`
	Validators           []*Validator `protobuf:"bytes,6,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Staking) Reset()         { *m = Staking{} }
func (m *Staking) String() string { return proto.CompactTextString(m) }
func (*Staking) ProtoMessage()    {}
func (*Staking) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6736eb38aebd97d, []int{2}
}

func (m *Staking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Staking.Unmarshal(m, b)
}
func (m *Staking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Staking.Marshal(b, m, deterministic)
}
func (m *Staking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staking.Merge(m, src)
}
func (m *Staking) XXX_Size() int {
	return xxx_messageInfo_Staking.Size(m)
}
func (m *Staking) XXX_DiscardUnknown() {
	xxx_messageInfo_Staking.DiscardUnknown(m)
}

var xxx_messageInfo_Staking proto.InternalMessageInfo

func (m *Staking) GetSession() int64 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *Staking) GetEra() int64 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *Staking) GetTotalStake() int64 {
	if m != nil {
		return m.TotalStake
	}
	return 0
}

func (m *Staking) GetTotalRewardPayout() int64 {
	if m != nil {
		return m.TotalRewardPayout
	}
	return 0
}

func (m *Staking) GetTotalRewardPoints() int64 {
	if m != nil {
		return m.TotalRewardPoints
	}
	return 0
}

func (m *Staking) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6736eb38aebd97d, []int{3}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Staking              *Staking `protobuf:"bytes,1,opt,name=staking,proto3" json:"staking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6736eb38aebd97d, []int{4}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetStaking() *Staking {
	if m != nil {
		return m.Staking
	}
	return nil
}

func init() {
	proto.RegisterType((*Stake)(nil), "staking.Stake")
	proto.RegisterType((*Validator)(nil), "staking.Validator")
	proto.RegisterType((*Staking)(nil), "staking.Staking")
	proto.RegisterType((*GetByHeightRequest)(nil), "staking.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "staking.GetByHeightResponse")
}

func init() {
	proto.RegisterFile("grpc/staking/stakingpb/staking.proto", fileDescriptor_c6736eb38aebd97d)
}

var fileDescriptor_c6736eb38aebd97d = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0x49, 0x4d, 0x92, 0x66, 0x36, 0x54, 0xad, 0x8b, 0x2a, 0x8b, 0x22, 0x08, 0x0b, 0x87,
	0x15, 0x82, 0x20, 0x85, 0x27, 0x68, 0x2f, 0x20, 0xb8, 0x20, 0x47, 0xe2, 0x80, 0x90, 0x22, 0x77,
	0x3b, 0x4a, 0xac, 0xa4, 0xf6, 0xd6, 0x76, 0x1a, 0xe5, 0xa9, 0x78, 0x2f, 0x9e, 0x02, 0x65, 0x6c,
	0x87, 0x94, 0xf4, 0xca, 0x69, 0x77, 0xfe, 0xff, 0xdf, 0x1d, 0xcf, 0x67, 0x1b, 0xde, 0x4c, 0x5d,
	0x53, 0x7f, 0xf0, 0x41, 0xcd, 0xb5, 0x99, 0xe6, 0x67, 0x73, 0x95, 0xdf, 0x86, 0x8d, 0xb3, 0xc1,
	0xf2, 0x6e, 0x2a, 0xcb, 0x5b, 0x68, 0x8f, 0x83, 0x9a, 0x23, 0x7f, 0x0d, 0x4f, 0x7c, 0x50, 0x7e,
	0x36, 0x51, 0x75, 0x6d, 0x97, 0x26, 0x88, 0xd6, 0xa0, 0x55, 0xf5, 0x64, 0x9f, 0xc4, 0x8b, 0xa8,
	0xf1, 0xf7, 0xc0, 0x6b, 0x6b, 0x82, 0xb3, 0x8b, 0x05, 0xba, 0x6d, 0xf2, 0x80, 0x92, 0x27, 0x7f,
	0x9d, 0x1c, 0x7f, 0x0a, 0xed, 0x4d, 0x1f, 0x14, 0x6c, 0xd0, 0xaa, 0x98, 0x8c, 0x45, 0xf9, 0xeb,
	0x00, 0x7a, 0xdf, 0xd5, 0x42, 0x5f, 0xab, 0x60, 0xdd, 0x7f, 0xe9, 0xfb, 0x02, 0xa0, 0xb6, 0x37,
	0x37, 0xda, 0x7b, 0x6d, 0x4d, 0x6a, 0xbe, 0xa3, 0x6c, 0x7a, 0x3a, 0x5c, 0x29, 0x77, 0x3d, 0x69,
	0xac, 0x36, 0xc1, 0x8b, 0xc7, 0x14, 0xe9, 0x47, 0xf1, 0x1b, 0x69, 0xfc, 0x25, 0x14, 0xc1, 0x06,
	0xb5, 0x98, 0xc4, 0x11, 0xda, 0xf1, 0x2f, 0x24, 0x45, 0x62, 0xe7, 0xd0, 0xb3, 0x2b, 0x93, 0xec,
	0x0e, 0xd9, 0x87, 0x76, 0x65, 0xa2, 0x59, 0x01, 0x21, 0x46, 0xe7, 0x45, 0x77, 0xc0, 0xaa, 0x62,
	0x74, 0x34, 0xcc, 0x3b, 0x40, 0x01, 0x99, 0x6d, 0xfe, 0x0a, 0xfa, 0x1e, 0x69, 0x5d, 0x93, 0x39,
	0xae, 0xbd, 0x38, 0x1c, 0xb0, 0xaa, 0x27, 0x8b, 0xa4, 0x7d, 0xc5, 0xb5, 0x2f, 0x7f, 0xb7, 0xa0,
	0x3b, 0x8e, 0x5f, 0x73, 0x01, 0xdd, 0x64, 0x11, 0x29, 0x26, 0x73, 0xc9, 0x8f, 0x81, 0xa1, 0x53,
	0x44, 0x85, 0xc9, 0xcd, 0xeb, 0xbf, 0x23, 0xb0, 0xbd, 0x11, 0x86, 0x70, 0x1a, 0x03, 0x19, 0x87,
	0x5a, 0xdb, 0x65, 0x48, 0x38, 0x4e, 0xc8, 0x92, 0x91, 0x09, 0x19, 0xfb, 0xf9, 0x88, 0xaf, 0xbd,
	0x9f, 0x8f, 0x0c, 0x47, 0x00, 0x77, 0x79, 0xa7, 0xbd, 0xe8, 0x10, 0x08, 0xbe, 0x05, 0xb1, 0x3d,
	0x04, 0x72, 0x27, 0x55, 0xbe, 0x03, 0xfe, 0x09, 0xc3, 0xe5, 0xfa, 0x33, 0xea, 0xe9, 0x2c, 0x48,
	0xbc, 0x5d, 0xa2, 0x0f, 0xfc, 0x0c, 0x3a, 0x33, 0x12, 0xd2, 0xd4, 0xa9, 0x2a, 0x2f, 0xe0, 0xf4,
	0x5e, 0xda, 0x37, 0xd6, 0x78, 0xe4, 0x6f, 0x21, 0x9f, 0x70, 0xca, 0x17, 0xa3, 0xe3, 0x7b, 0xf8,
	0xb5, 0x99, 0xca, 0x1c, 0x18, 0xfd, 0x84, 0xa3, 0xa4, 0x8d, 0xd1, 0xdd, 0xe9, 0x1a, 0xf9, 0x17,
	0x28, 0x76, 0x7e, 0xca, 0xcf, 0xb7, 0xdf, 0xee, 0x2f, 0xec, 0xd9, 0xf3, 0x87, 0xcd, 0xb8, 0x8e,
	0xf2, 0xd1, 0xa5, 0xf8, 0x71, 0xf6, 0xf0, 0x8d, 0xbc, 0xea, 0xd0, 0x55, 0xfc, 0xf8, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0x2e, 0x26, 0xef, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StakingServiceClient is the client API for StakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StakingServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type stakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStakingServiceClient(cc grpc.ClientConnInterface) StakingServiceClient {
	return &stakingServiceClient{cc}
}

func (c *stakingServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/staking.StakingService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakingServiceServer is the server API for StakingService service.
type StakingServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedStakingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStakingServiceServer struct {
}

func (*UnimplementedStakingServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterStakingServiceServer(s *grpc.Server, srv StakingServiceServer) {
	s.RegisterService(&_StakingService_serviceDesc, srv)
}

func _StakingService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/staking.StakingService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StakingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "staking.StakingService",
	HandlerType: (*StakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _StakingService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/staking/stakingpb/staking.proto",
}
