// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/account/accountpb/account.proto

package accountpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ReferendumCount      int64    `protobuf:"varint,2,opt,name=referendum_count,json=referendumCount,proto3" json:"referendum_count,omitempty"`
	Free                 string   `protobuf:"bytes,3,opt,name=free,proto3" json:"free,omitempty"`
	Reserved             string   `protobuf:"bytes,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	MiscFrozen           string   `protobuf:"bytes,5,opt,name=misc_frozen,json=miscFrozen,proto3" json:"misc_frozen,omitempty"`
	FeeFrozen            string   `protobuf:"bytes,6,opt,name=fee_frozen,json=feeFrozen,proto3" json:"fee_frozen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetReferendumCount() int64 {
	if m != nil {
		return m.ReferendumCount
	}
	return 0
}

func (m *Account) GetFree() string {
	if m != nil {
		return m.Free
	}
	return ""
}

func (m *Account) GetReserved() string {
	if m != nil {
		return m.Reserved
	}
	return ""
}

func (m *Account) GetMiscFrozen() string {
	if m != nil {
		return m.MiscFrozen
	}
	return ""
}

func (m *Account) GetFeeFrozen() string {
	if m != nil {
		return m.FeeFrozen
	}
	return ""
}

type AccountIdentity struct {
	Deposit              string   `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	LegalName            string   `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	WebName              string   `protobuf:"bytes,4,opt,name=web_name,json=webName,proto3" json:"web_name,omitempty"`
	RiotName             string   `protobuf:"bytes,5,opt,name=riot_name,json=riotName,proto3" json:"riot_name,omitempty"`
	EmailName            string   `protobuf:"bytes,6,opt,name=email_name,json=emailName,proto3" json:"email_name,omitempty"`
	TwitterName          string   `protobuf:"bytes,7,opt,name=twitter_name,json=twitterName,proto3" json:"twitter_name,omitempty"`
	Image                string   `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountIdentity) Reset()         { *m = AccountIdentity{} }
func (m *AccountIdentity) String() string { return proto.CompactTextString(m) }
func (*AccountIdentity) ProtoMessage()    {}
func (*AccountIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{1}
}

func (m *AccountIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountIdentity.Unmarshal(m, b)
}
func (m *AccountIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountIdentity.Marshal(b, m, deterministic)
}
func (m *AccountIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountIdentity.Merge(m, src)
}
func (m *AccountIdentity) XXX_Size() int {
	return xxx_messageInfo_AccountIdentity.Size(m)
}
func (m *AccountIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_AccountIdentity proto.InternalMessageInfo

func (m *AccountIdentity) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *AccountIdentity) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AccountIdentity) GetLegalName() string {
	if m != nil {
		return m.LegalName
	}
	return ""
}

func (m *AccountIdentity) GetWebName() string {
	if m != nil {
		return m.WebName
	}
	return ""
}

func (m *AccountIdentity) GetRiotName() string {
	if m != nil {
		return m.RiotName
	}
	return ""
}

func (m *AccountIdentity) GetEmailName() string {
	if m != nil {
		return m.EmailName
	}
	return ""
}

func (m *AccountIdentity) GetTwitterName() string {
	if m != nil {
		return m.TwitterName
	}
	return ""
}

func (m *AccountIdentity) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type GetIdentityRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentityRequest) Reset()         { *m = GetIdentityRequest{} }
func (m *GetIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentityRequest) ProtoMessage()    {}
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{2}
}

func (m *GetIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityRequest.Unmarshal(m, b)
}
func (m *GetIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityRequest.Marshal(b, m, deterministic)
}
func (m *GetIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityRequest.Merge(m, src)
}
func (m *GetIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentityRequest.Size(m)
}
func (m *GetIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityRequest proto.InternalMessageInfo

func (m *GetIdentityRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetIdentityResponse struct {
	Identity             *AccountIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetIdentityResponse) Reset()         { *m = GetIdentityResponse{} }
func (m *GetIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*GetIdentityResponse) ProtoMessage()    {}
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{3}
}

func (m *GetIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentityResponse.Unmarshal(m, b)
}
func (m *GetIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentityResponse.Marshal(b, m, deterministic)
}
func (m *GetIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentityResponse.Merge(m, src)
}
func (m *GetIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_GetIdentityResponse.Size(m)
}
func (m *GetIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentityResponse proto.InternalMessageInfo

func (m *GetIdentityResponse) GetIdentity() *AccountIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{4}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetByHeightRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetByHeightResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{5}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*AccountIdentity)(nil), "account.AccountIdentity")
	proto.RegisterType((*GetIdentityRequest)(nil), "account.GetIdentityRequest")
	proto.RegisterType((*GetIdentityResponse)(nil), "account.GetIdentityResponse")
	proto.RegisterType((*GetByHeightRequest)(nil), "account.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "account.GetByHeightResponse")
}

func init() {
	proto.RegisterFile("grpc/account/accountpb/account.proto", fileDescriptor_3b4bc31470b810eb)
}

var fileDescriptor_3b4bc31470b810eb = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x5d, 0xb6, 0xb5, 0x69, 0xbe, 0x4e, 0x6c, 0x32, 0xd3, 0x64, 0x36, 0x10, 0x5b, 0xc4, 0xc5,
	0xe0, 0xa2, 0x48, 0x83, 0x17, 0xd8, 0x90, 0xc6, 0x9f, 0xc4, 0x45, 0xb8, 0xe3, 0xa6, 0x72, 0x93,
	0x2f, 0x9d, 0xa5, 0xc6, 0x0e, 0xb6, 0xbb, 0xaa, 0x3c, 0x11, 0xcf, 0xc0, 0xbb, 0x21, 0xa1, 0x7e,
	0xb6, 0xbb, 0x35, 0xf4, 0x2a, 0xfe, 0xce, 0x39, 0x39, 0x3e, 0xc7, 0xb2, 0xe1, 0xd5, 0xd4, 0xb4,
	0xe5, 0x5b, 0x51, 0x96, 0x7a, 0xae, 0x5c, 0xfc, 0xb6, 0x93, 0xb8, 0x1a, 0xb5, 0x46, 0x3b, 0xcd,
	0xd2, 0x30, 0xe6, 0x7f, 0x12, 0x48, 0xaf, 0xfd, 0x9a, 0x1d, 0x43, 0x4f, 0x69, 0x55, 0x22, 0x4f,
	0xce, 0x93, 0xcb, 0xbd, 0xc2, 0x0f, 0xec, 0x35, 0x1c, 0x19, 0xac, 0xd1, 0xa0, 0xaa, 0xe6, 0xcd,
	0x98, 0x94, 0x7c, 0x97, 0x04, 0x87, 0x0f, 0xf8, 0x07, 0x32, 0x60, 0xb0, 0x5f, 0x1b, 0x44, 0xbe,
	0x77, 0x9e, 0x5c, 0x66, 0x05, 0xad, 0xd9, 0x29, 0x0c, 0x0c, 0x5a, 0x34, 0xf7, 0x58, 0xf1, 0x7d,
	0xc2, 0xd7, 0x33, 0x7b, 0x09, 0xc3, 0x46, 0xda, 0x72, 0x5c, 0x1b, 0xfd, 0x0b, 0x15, 0xef, 0x11,
	0x0d, 0x2b, 0xe8, 0x96, 0x10, 0xf6, 0x02, 0xa0, 0x46, 0x8c, 0x7c, 0x9f, 0xf8, 0xac, 0x46, 0xf4,
	0x74, 0xfe, 0x37, 0x81, 0xc3, 0x10, 0xfe, 0x73, 0x85, 0xca, 0x49, 0xb7, 0x64, 0x1c, 0xd2, 0x0a,
	0x5b, 0x6d, 0xa5, 0xa3, 0x1a, 0x59, 0x11, 0x47, 0x76, 0x01, 0x07, 0x95, 0xb4, 0xed, 0x4c, 0x2c,
	0xc7, 0x4a, 0x34, 0x48, 0x25, 0xb2, 0x62, 0x18, 0xb0, 0x6f, 0xa2, 0xc1, 0xd5, 0x7e, 0x33, 0x9c,
	0x8a, 0x99, 0x17, 0xf8, 0x1a, 0x19, 0x21, 0x44, 0x3f, 0x83, 0xc1, 0x02, 0x27, 0x9e, 0xf4, 0x5d,
	0xd2, 0x05, 0x4e, 0x88, 0x3a, 0x83, 0xcc, 0x48, 0xed, 0x3c, 0xd7, 0x0b, 0x3d, 0xa5, 0x76, 0xd1,
	0x16, 0x1b, 0x21, 0x83, 0x6d, 0xa8, 0x41, 0x08, 0xd1, 0x17, 0x70, 0xe0, 0x16, 0xd2, 0x39, 0x34,
	0x5e, 0x90, 0xfa, 0x60, 0x01, 0x23, 0xc9, 0x31, 0xf4, 0x64, 0x23, 0xa6, 0xc8, 0x07, 0xc4, 0xf9,
	0x21, 0x1f, 0x01, 0xfb, 0x88, 0xeb, 0xea, 0x05, 0xfe, 0x9c, 0xa3, 0x75, 0xab, 0x13, 0x10, 0x55,
	0x65, 0xd0, 0xda, 0x78, 0x02, 0x61, 0xcc, 0xbf, 0xc2, 0xd3, 0x0d, 0xbd, 0x6d, 0xb5, 0xb2, 0xc8,
	0xde, 0xc3, 0x40, 0x06, 0x8c, 0xfe, 0x18, 0x5e, 0xf1, 0x51, 0xbc, 0x2e, 0x9d, 0xe3, 0x2d, 0xd6,
	0xca, 0xfc, 0x96, 0x36, 0xbf, 0x59, 0x7e, 0x42, 0x39, 0xbd, 0x73, 0x71, 0xf3, 0x13, 0xe8, 0xdf,
	0x11, 0x10, 0x2e, 0x51, 0x98, 0x1e, 0x87, 0xda, 0xdd, 0x0c, 0x75, 0x4d, 0xa1, 0x1e, 0x7c, 0x42,
	0xa8, 0x37, 0x10, 0xef, 0x68, 0xc8, 0x74, 0xd4, 0xcd, 0x54, 0x44, 0xc1, 0xd5, 0xef, 0x04, 0x9e,
	0x04, 0xf0, 0x3b, 0x9a, 0x7b, 0x59, 0x22, 0xfb, 0x02, 0xc3, 0x47, 0x55, 0xd9, 0xd9, 0xfa, 0xe7,
	0xff, 0x0f, 0xec, 0xf4, 0xf9, 0x76, 0xd2, 0x07, 0xc9, 0x77, 0x82, 0x57, 0x4c, 0xb8, 0xe9, 0xd5,
	0xe9, 0xbf, 0xe9, 0xd5, 0x2d, 0x95, 0xef, 0xdc, 0xf0, 0x1f, 0x27, 0xdb, 0x1f, 0xe8, 0xa4, 0x4f,
	0x2f, 0xf3, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xcb, 0x0d, 0x63, 0xc1, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// Fixed queries
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error)
	// Height queries
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error) {
	out := new(GetIdentityResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// Fixed queries
	GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error)
	// Height queries
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) GetIdentity(ctx context.Context, req *GetIdentityRequest) (*GetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (*UnimplementedAccountServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentity",
			Handler:    _AccountService_GetIdentity_Handler,
		},
		{
			MethodName: "GetByHeight",
			Handler:    _AccountService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/account/accountpb/account.proto",
}
