// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/chain/chainpb/chain.proto

package chainpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHeadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHeadRequest) Reset()         { *m = GetHeadRequest{} }
func (m *GetHeadRequest) String() string { return proto.CompactTextString(m) }
func (*GetHeadRequest) ProtoMessage()    {}
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{0}
}

func (m *GetHeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeadRequest.Unmarshal(m, b)
}
func (m *GetHeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeadRequest.Marshal(b, m, deterministic)
}
func (m *GetHeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeadRequest.Merge(m, src)
}
func (m *GetHeadRequest) XXX_Size() int {
	return xxx_messageInfo_GetHeadRequest.Size(m)
}
func (m *GetHeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeadRequest proto.InternalMessageInfo

type GetHeadResponse struct {
	Height               int64                `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Session              int64                `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`
	Era                  int64                `protobuf:"varint,4,opt,name=era,proto3" json:"era,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetHeadResponse) Reset()         { *m = GetHeadResponse{} }
func (m *GetHeadResponse) String() string { return proto.CompactTextString(m) }
func (*GetHeadResponse) ProtoMessage()    {}
func (*GetHeadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{1}
}

func (m *GetHeadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeadResponse.Unmarshal(m, b)
}
func (m *GetHeadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeadResponse.Marshal(b, m, deterministic)
}
func (m *GetHeadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeadResponse.Merge(m, src)
}
func (m *GetHeadResponse) XXX_Size() int {
	return xxx_messageInfo_GetHeadResponse.Size(m)
}
func (m *GetHeadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeadResponse proto.InternalMessageInfo

func (m *GetHeadResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetHeadResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GetHeadResponse) GetSession() int64 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *GetHeadResponse) GetEra() int64 {
	if m != nil {
		return m.Era
	}
	return 0
}

type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{2}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	ClientInfo           string            `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	ChainName            string            `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	ChainType            string            `protobuf:"bytes,3,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	NodeName             string            `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeHealth           string            `protobuf:"bytes,5,opt,name=node_health,json=nodeHealth,proto3" json:"node_health,omitempty"`
	NodeRoles            []string          `protobuf:"bytes,6,rep,name=node_roles,json=nodeRoles,proto3" json:"node_roles,omitempty"`
	NodeVersion          string            `protobuf:"bytes,7,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	NodeLocalPeerUid     string            `protobuf:"bytes,8,opt,name=node_local_peer_uid,json=nodeLocalPeerUid,proto3" json:"node_local_peer_uid,omitempty"`
	NodeProperties       map[string]string `protobuf:"bytes,9,rep,name=node_properties,json=nodeProperties,proto3" json:"node_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GenesisHash          string            `protobuf:"bytes,10,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{3}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetClientInfo() string {
	if m != nil {
		return m.ClientInfo
	}
	return ""
}

func (m *GetStatusResponse) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *GetStatusResponse) GetChainType() string {
	if m != nil {
		return m.ChainType
	}
	return ""
}

func (m *GetStatusResponse) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *GetStatusResponse) GetNodeHealth() string {
	if m != nil {
		return m.NodeHealth
	}
	return ""
}

func (m *GetStatusResponse) GetNodeRoles() []string {
	if m != nil {
		return m.NodeRoles
	}
	return nil
}

func (m *GetStatusResponse) GetNodeVersion() string {
	if m != nil {
		return m.NodeVersion
	}
	return ""
}

func (m *GetStatusResponse) GetNodeLocalPeerUid() string {
	if m != nil {
		return m.NodeLocalPeerUid
	}
	return ""
}

func (m *GetStatusResponse) GetNodeProperties() map[string]string {
	if m != nil {
		return m.NodeProperties
	}
	return nil
}

func (m *GetStatusResponse) GetGenesisHash() string {
	if m != nil {
		return m.GenesisHash
	}
	return ""
}

type GetMetaByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaByHeightRequest) Reset()         { *m = GetMetaByHeightRequest{} }
func (m *GetMetaByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetaByHeightRequest) ProtoMessage()    {}
func (*GetMetaByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{4}
}

func (m *GetMetaByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetaByHeightRequest.Unmarshal(m, b)
}
func (m *GetMetaByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetaByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetMetaByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaByHeightRequest.Merge(m, src)
}
func (m *GetMetaByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetaByHeightRequest.Size(m)
}
func (m *GetMetaByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaByHeightRequest proto.InternalMessageInfo

func (m *GetMetaByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetMetaByHeightResponse struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Session              int64                `protobuf:"varint,2,opt,name=session,proto3" json:"session,omitempty"`
	Era                  int64                `protobuf:"varint,3,opt,name=era,proto3" json:"era,omitempty"`
	LastInSession        bool                 `protobuf:"varint,4,opt,name=last_in_session,json=lastInSession,proto3" json:"last_in_session,omitempty"`
	LastInEra            bool                 `protobuf:"varint,5,opt,name=last_in_era,json=lastInEra,proto3" json:"last_in_era,omitempty"`
	Chain                string               `protobuf:"bytes,6,opt,name=chain,proto3" json:"chain,omitempty"`
	SpecVersion          string               `protobuf:"bytes,7,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMetaByHeightResponse) Reset()         { *m = GetMetaByHeightResponse{} }
func (m *GetMetaByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetaByHeightResponse) ProtoMessage()    {}
func (*GetMetaByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{5}
}

func (m *GetMetaByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetaByHeightResponse.Unmarshal(m, b)
}
func (m *GetMetaByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetaByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetMetaByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaByHeightResponse.Merge(m, src)
}
func (m *GetMetaByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetaByHeightResponse.Size(m)
}
func (m *GetMetaByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaByHeightResponse proto.InternalMessageInfo

func (m *GetMetaByHeightResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GetMetaByHeightResponse) GetSession() int64 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *GetMetaByHeightResponse) GetEra() int64 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *GetMetaByHeightResponse) GetLastInSession() bool {
	if m != nil {
		return m.LastInSession
	}
	return false
}

func (m *GetMetaByHeightResponse) GetLastInEra() bool {
	if m != nil {
		return m.LastInEra
	}
	return false
}

func (m *GetMetaByHeightResponse) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *GetMetaByHeightResponse) GetSpecVersion() string {
	if m != nil {
		return m.SpecVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHeadRequest)(nil), "chain.GetHeadRequest")
	proto.RegisterType((*GetHeadResponse)(nil), "chain.GetHeadResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "chain.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "chain.GetStatusResponse")
	proto.RegisterMapType((map[string]string)(nil), "chain.GetStatusResponse.NodePropertiesEntry")
	proto.RegisterType((*GetMetaByHeightRequest)(nil), "chain.GetMetaByHeightRequest")
	proto.RegisterType((*GetMetaByHeightResponse)(nil), "chain.GetMetaByHeightResponse")
}

func init() { proto.RegisterFile("grpc/chain/chainpb/chain.proto", fileDescriptor_ce694d07bea9bb01) }

var fileDescriptor_ce694d07bea9bb01 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x4f, 0xdb, 0x4c,
	0x10, 0xc5, 0x98, 0x04, 0x3c, 0xe1, 0x83, 0x7c, 0x0b, 0x85, 0x55, 0x2a, 0x20, 0xf5, 0xa1, 0xe2,
	0xd0, 0x9a, 0x8a, 0x5e, 0x2a, 0x4e, 0x2d, 0x15, 0x22, 0x48, 0x2d, 0x42, 0x06, 0x7a, 0xe8, 0x25,
	0x5a, 0x92, 0x21, 0xb6, 0x6a, 0x76, 0xdd, 0xdd, 0x0d, 0x52, 0x7e, 0x40, 0xff, 0x66, 0xd5, 0x5f,
	0xd1, 0x73, 0xb5, 0xb3, 0x76, 0xa0, 0x04, 0x0e, 0xbd, 0x24, 0xde, 0x37, 0x6f, 0xde, 0x8e, 0xe6,
	0x3d, 0x1b, 0xb6, 0x47, 0xba, 0x1c, 0xec, 0x0d, 0x32, 0x91, 0x4b, 0xff, 0x5b, 0x5e, 0xf9, 0xff,
	0xa4, 0xd4, 0xca, 0x2a, 0xd6, 0xa0, 0x43, 0x67, 0x67, 0xa4, 0xd4, 0xa8, 0xc0, 0x3d, 0x02, 0xaf,
	0xc6, 0xd7, 0x7b, 0x36, 0xbf, 0x41, 0x63, 0xc5, 0x4d, 0xe9, 0x79, 0x71, 0x1b, 0x56, 0x8e, 0xd1,
	0xf6, 0x50, 0x0c, 0x53, 0xfc, 0x3e, 0x46, 0x63, 0xe3, 0x1f, 0x01, 0xac, 0x4e, 0x21, 0x53, 0x2a,
	0x69, 0x90, 0x6d, 0x40, 0x33, 0xc3, 0x7c, 0x94, 0x59, 0x1e, 0x74, 0x83, 0xdd, 0x30, 0xad, 0x4e,
	0x2c, 0x81, 0x05, 0x27, 0xc8, 0xe7, 0xbb, 0xc1, 0x6e, 0x6b, 0xbf, 0x93, 0xf8, 0xdb, 0x92, 0xfa,
	0xb6, 0xe4, 0xa2, 0xbe, 0x2d, 0x25, 0x1e, 0xe3, 0xb0, 0x68, 0xd0, 0x98, 0x5c, 0x49, 0x1e, 0x92,
	0x50, 0x7d, 0x64, 0x6d, 0x08, 0x51, 0x0b, 0xbe, 0x40, 0xa8, 0x7b, 0x8c, 0x19, 0xb4, 0x8f, 0xd1,
	0x9e, 0x5b, 0x61, 0xc7, 0xa6, 0x9e, 0xed, 0x67, 0x08, 0xff, 0xdf, 0x03, 0xab, 0xe9, 0x76, 0xa0,
	0x35, 0x28, 0x72, 0x94, 0xb6, 0x9f, 0xcb, 0x6b, 0x45, 0x23, 0x46, 0x29, 0x78, 0xe8, 0x44, 0x5e,
	0x2b, 0xb6, 0x05, 0x40, 0xeb, 0xe8, 0x4b, 0x51, 0x0d, 0x1b, 0xa5, 0x11, 0x21, 0xa7, 0xe2, 0x06,
	0xef, 0xca, 0x76, 0x52, 0x22, 0x0d, 0x56, 0x97, 0x2f, 0x26, 0x25, 0xb2, 0xe7, 0x10, 0x49, 0x35,
	0x44, 0xdf, 0xbc, 0x40, 0xd5, 0x25, 0x07, 0x50, 0xef, 0x0e, 0xb4, 0xa8, 0x98, 0xa1, 0x28, 0x6c,
	0xc6, 0x1b, 0xfe, 0x6e, 0x07, 0xf5, 0x08, 0x71, 0xe2, 0x44, 0xd0, 0xaa, 0x40, 0xc3, 0x9b, 0xdd,
	0xd0, 0x89, 0x3b, 0x24, 0x75, 0x00, 0x7b, 0x01, 0xcb, 0x54, 0xbe, 0x45, 0x4d, 0x6b, 0x59, 0x24,
	0x01, 0xd2, 0xfc, 0xe2, 0x21, 0xf6, 0x1a, 0xd6, 0x88, 0x52, 0xa8, 0x81, 0x28, 0xfa, 0x25, 0xa2,
	0xee, 0x8f, 0xf3, 0x21, 0x5f, 0x22, 0x66, 0xdb, 0x95, 0x3e, 0xb9, 0xca, 0x19, 0xa2, 0xbe, 0xcc,
	0x87, 0xec, 0x12, 0x56, 0x89, 0x5e, 0x6a, 0x55, 0xa2, 0xb6, 0x39, 0x1a, 0x1e, 0x75, 0xc3, 0xdd,
	0xd6, 0xfe, 0xab, 0xc4, 0x07, 0x64, 0x66, 0x81, 0xc9, 0xa9, 0x1a, 0xe2, 0xd9, 0x94, 0x7e, 0x24,
	0xad, 0x9e, 0xa4, 0x2b, 0xf2, 0x2f, 0xd0, 0x0d, 0x3a, 0x42, 0x89, 0x26, 0x37, 0xfd, 0x4c, 0x98,
	0x8c, 0x83, 0x1f, 0xb4, 0xc2, 0x7a, 0xc2, 0x64, 0x9d, 0x0f, 0xb0, 0xf6, 0x88, 0x92, 0xb3, 0xf6,
	0x1b, 0x4e, 0x2a, 0x5b, 0xdc, 0x23, 0x5b, 0x87, 0xc6, 0xad, 0x28, 0xc6, 0xb5, 0x15, 0xfe, 0x70,
	0x30, 0xff, 0x2e, 0x88, 0xdf, 0xc0, 0xc6, 0x31, 0xda, 0xcf, 0x68, 0xc5, 0xe1, 0xa4, 0x47, 0x19,
	0xab, 0xac, 0x7f, 0x2a, 0x82, 0xf1, 0xef, 0x00, 0x36, 0x67, 0x5a, 0xaa, 0x60, 0xd4, 0xf1, 0x0c,
	0xfe, 0x3d, 0x9e, 0xf3, 0x8f, 0xc6, 0x33, 0x9c, 0xc6, 0x93, 0xbd, 0x84, 0xd5, 0x42, 0x18, 0x17,
	0xb9, 0x7e, 0xdd, 0xe3, 0xb2, 0xb1, 0x94, 0xfe, 0xe7, 0xe0, 0x13, 0x79, 0x5e, 0x75, 0x6e, 0x43,
	0xab, 0xe6, 0x39, 0x85, 0x06, 0x71, 0x22, 0xcf, 0x39, 0xd2, 0xc2, 0xed, 0x82, 0x6c, 0xe1, 0x4d,
	0xbf, 0x0b, 0x3a, 0xb8, 0x6d, 0x9b, 0x12, 0x07, 0x0f, 0x63, 0xe1, 0xb0, 0x2a, 0x16, 0xfb, 0xbf,
	0x02, 0x58, 0xfe, 0xe8, 0xc8, 0xe7, 0xa8, 0x6f, 0xf3, 0x01, 0xb2, 0x03, 0x58, 0xac, 0xde, 0x5b,
	0xf6, 0xec, 0xce, 0xea, 0x7b, 0xaf, 0x76, 0x67, 0xe3, 0x21, 0xec, 0xf7, 0x14, 0xcf, 0xb1, 0xf7,
	0x10, 0x4d, 0x63, 0xc1, 0x36, 0x67, 0x83, 0xe2, 0xfb, 0xf9, 0x53, 0x09, 0x8a, 0xe7, 0x58, 0x4a,
	0x5f, 0x8d, 0xfb, 0x36, 0xb0, 0xad, 0x3b, 0xfa, 0x23, 0x8e, 0x76, 0xb6, 0x9f, 0x2a, 0xd7, 0x9a,
	0x87, 0xeb, 0x5f, 0xd9, 0xec, 0x67, 0xee, 0xaa, 0x49, 0xfe, 0xbd, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x01, 0x1a, 0x95, 0x03, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChainServiceClient is the client API for ChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainServiceClient interface {
	GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetMetaByHeight(ctx context.Context, in *GetMetaByHeightRequest, opts ...grpc.CallOption) (*GetMetaByHeightResponse, error)
}

type chainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainServiceClient(cc grpc.ClientConnInterface) ChainServiceClient {
	return &chainServiceClient{cc}
}

func (c *chainServiceClient) GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error) {
	out := new(GetHeadResponse)
	err := c.cc.Invoke(ctx, "/chain.ChainService/GetHead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/chain.ChainService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainServiceClient) GetMetaByHeight(ctx context.Context, in *GetMetaByHeightRequest, opts ...grpc.CallOption) (*GetMetaByHeightResponse, error) {
	out := new(GetMetaByHeightResponse)
	err := c.cc.Invoke(ctx, "/chain.ChainService/GetMetaByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainServiceServer is the server API for ChainService service.
type ChainServiceServer interface {
	GetHead(context.Context, *GetHeadRequest) (*GetHeadResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetMetaByHeight(context.Context, *GetMetaByHeightRequest) (*GetMetaByHeightResponse, error)
}

// UnimplementedChainServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChainServiceServer struct {
}

func (*UnimplementedChainServiceServer) GetHead(ctx context.Context, req *GetHeadRequest) (*GetHeadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHead not implemented")
}
func (*UnimplementedChainServiceServer) GetStatus(ctx context.Context, req *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedChainServiceServer) GetMetaByHeight(ctx context.Context, req *GetMetaByHeightRequest) (*GetMetaByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaByHeight not implemented")
}

func RegisterChainServiceServer(s *grpc.Server, srv ChainServiceServer) {
	s.RegisterService(&_ChainService_serviceDesc, srv)
}

func _ChainService_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServiceServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.ChainService/GetHead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServiceServer).GetHead(ctx, req.(*GetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.ChainService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainService_GetMetaByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServiceServer).GetMetaByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.ChainService/GetMetaByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServiceServer).GetMetaByHeight(ctx, req.(*GetMetaByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.ChainService",
	HandlerType: (*ChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHead",
			Handler:    _ChainService_GetHead_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ChainService_GetStatus_Handler,
		},
		{
			MethodName: "GetMetaByHeight",
			Handler:    _ChainService_GetMetaByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/chain/chainpb/chain.proto",
}
