// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/event/eventpb/event.proto

package eventpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Phase                string   `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Section              string   `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	ExtrinsicIndex       int64    `protobuf:"varint,6,opt,name=extrinsicIndex,proto3" json:"extrinsicIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_510be368b1a45811, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Event) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *Event) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Event) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *Event) GetExtrinsicIndex() int64 {
	if m != nil {
		return m.ExtrinsicIndex
	}
	return 0
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_510be368b1a45811, []int{1}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_510be368b1a45811, []int{2}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*GetByHeightRequest)(nil), "event.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "event.GetByHeightResponse")
}

func init() { proto.RegisterFile("grpc/event/eventpb/event.proto", fileDescriptor_510be368b1a45811) }

var fileDescriptor_510be368b1a45811 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x31, 0x69, 0x82, 0xb8, 0x56, 0x0c, 0x47, 0x85, 0x4c, 0x07, 0x14, 0x45, 0x08, 0x65,
	0x40, 0x45, 0x2a, 0x23, 0x5b, 0x25, 0xfe, 0xad, 0x41, 0x62, 0x60, 0x4b, 0x93, 0x53, 0xe3, 0x01,
	0xdb, 0xc4, 0xa6, 0x2a, 0x8f, 0xc3, 0x9b, 0xa2, 0x9c, 0x8d, 0x04, 0x94, 0x25, 0xb9, 0xdf, 0x77,
	0x67, 0x7f, 0x77, 0x3e, 0x38, 0x5b, 0xf7, 0xb6, 0xb9, 0xa2, 0x0d, 0x69, 0x1f, 0xbe, 0x76, 0x15,
	0xfe, 0x73, 0xdb, 0x1b, 0x6f, 0x30, 0x65, 0x28, 0x3e, 0x05, 0xa4, 0xb7, 0x43, 0x84, 0x53, 0x48,
	0x95, 0x6e, 0x69, 0x2b, 0x45, 0x2e, 0xca, 0xa4, 0x0a, 0x80, 0x08, 0xa3, 0xb6, 0xf6, 0xb5, 0xdc,
	0xcf, 0x45, 0x79, 0x58, 0x71, 0x3c, 0x54, 0xda, 0xae, 0x76, 0x24, 0x13, 0x16, 0x03, 0xe0, 0x09,
	0x64, 0xaf, 0xe4, 0x3b, 0xd3, 0xca, 0x11, 0xcb, 0x91, 0x50, 0xc2, 0x81, 0xa3, 0xc6, 0x2b, 0xa3,
	0x65, 0xca, 0x89, 0x6f, 0xc4, 0x0b, 0x38, 0xa2, 0xad, 0xef, 0x95, 0x76, 0xaa, 0x79, 0x64, 0xeb,
	0x8c, 0xad, 0xff, 0xa8, 0xc5, 0x25, 0xe0, 0x3d, 0xf9, 0xe5, 0xc7, 0x03, 0xa9, 0x75, 0xe7, 0x2b,
	0x7a, 0x7b, 0x27, 0xe7, 0x07, 0xbf, 0x8e, 0x85, 0xd8, 0x70, 0xa4, 0xe2, 0x06, 0x8e, 0x7f, 0x55,
	0x3b, 0x6b, 0xb4, 0x23, 0x3c, 0x87, 0x8c, 0x27, 0x76, 0x52, 0xe4, 0x49, 0x39, 0x5e, 0x4c, 0xe6,
	0xe1, 0x35, 0x78, 0xf8, 0x2a, 0xe6, 0x16, 0xcf, 0x30, 0x61, 0xe1, 0x89, 0xfa, 0x8d, 0x6a, 0x08,
	0xef, 0x60, 0xfc, 0xe3, 0x32, 0x3c, 0x8d, 0x87, 0x76, 0xdb, 0x99, 0xcd, 0xfe, 0x4b, 0x05, 0xef,
	0x62, 0x6f, 0x39, 0x7d, 0xc1, 0xdd, 0x7d, 0xac, 0x32, 0x5e, 0xc5, 0xf5, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x09, 0x1d, 0x54, 0x01, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _EventService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/event/eventpb/event.proto",
}
