name: Polkadothub Proxy
# This workflow is triggered on pushes to the repository only when pushing new tag.
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Set ref vars
        id: refs
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push Docker image
        id: publish-docker-image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: figmentnetworks/polkadothub-proxy
          tags: latest
